{% set name = "pokemonpy-package" %}
{% set version = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/4ntoined/pokemonpy-package/archive/v{{ version }}.tar.gz
  sha256: 3fcc7c403d7fccedf746658b431f1df1e9d203f8f07b3e7a48839d4bddaa9a61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - numpy >=1.26.4,<1.27.dev0

test:
  imports:
    - pokemonpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/4ntoined/pokemonpy-package
  summary: A package that contains a Pokémon simulation game.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 4ntoined
